---
title: "**Data Processing - Course Project**"
author: "3DCP Helper"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, fig.align="center")

packages <- c(
  'ggplot2',
  'ggrepel',
  'patchwork',
  'ggraph',
  'dplyr',
  'gganimate',
  'gifski',
  'ggforce',
  'ggthemes',
  'maps',
  'sf',
  'tidyr',
  'concaveman',
  'remotes',
  'scales',
  'lubridate',
  'plotly',
  'gapminder',
  'stringr',
  'readr'
)


library(ggplot2)
library(scales)
library(lubridate)
library(plotly)
library(gapminder)
library(stringr)
library(readr)
library(dplyr)

suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(scales)))
suppressWarnings(suppressMessages(library(lubridate)))
suppressWarnings(suppressMessages(library(plotly)))
suppressWarnings(suppressMessages(library(gapminder)))
suppressWarnings(suppressMessages(library(readr)))
```



```{r load data, echo=FALSE}

script <- readLines("SmallPlate1.mpf") # Reading in the script and removing whitespace, =;><-# and other marks from the text. I only want the code left.

#script.ws <- trimws(script) %>%
  #str_replace_all("\t","") %>%
  #str_replace_all(">","") %>%
  #str_replace_all("<","") %>%
  #str_replace_na(replacement = "NA") %>%
  #str_replace_all("#","") %>% #replacing # with empty space
  #str_remove(";.+") %>% #Removing certain parts of the code starting with ;
  #str_remove("T.+") %>% # Remove starting with T
  #str_remove("R1.+") %>% # Remove starting with R1
  #str_remove("H.+") %>% # Remove starting with H
  #str_remove("M.+") %>% # Remove starting with M
  #str_remove("BS.+") %>% # Remove starting with BS
  #str_remove("F.+") %>% # Remove starting with F
  #str_remove("C.+") %>% # Remove starting with C
  #str_trim(side = "both")# Remove starting with Trimming whitespace

script2 <- str_extract_all(script, "((?<=X(?=\\d))\\d.\\d{1,})|((?<=X-(?=\\d))\\d.\\d{1,})", simplify = TRUE)
 # str_extract_all("X-\\d+.\\d+") %>%
 # str_extract_all("Y\\d+.\\d+") #%>%
 # str_extract("Y-\\d+.\\d+") # %>%
 # str_extract("Z\\d+.\\d+") %>%
 # str_extract("Z-\\d+.\\d+")
    

#script2[sapply(script2, nchar) > 0] # Removing empty lines from the script



finalfile<-file("output.mpf")   # Making a text document as output
writeLines(script2, finalfile)
close(finalfile)



# "(Z-\\d+.\\d+) (Z\\d+.\\d+) (X-\\d+.\\d+) (X\\d+.\\d+) (Y-\\d+.\\d+) (Y\\d+.\\d+)"
#my_new_file = current_file[-(15:18)]   this is to remove certain number of lines




#Check if the line contains a comment, if so remove it
#As result Rest of the file is code
#Reading in the XYZ values for incremental and absolute coordinates, if absolute coordinate just display (if incremental then calculate)





```

